"""empty message

Revision ID: 34af39438f9c
Revises: 98ed1847e728
Create Date: 2025-05-26 23:53:06.483612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34af39438f9c'
down_revision = '98ed1847e728'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Email', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('Email')

    # ### end Alembic commands ###
